# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-pgdb-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.9.1
  - conda-forge::markdown=3.3.3
  - conda-forge::pymdown-extensions=8.1
  - conda-forge::pygments=2.7.4
  # All the dependencies of the pipeline.
  - bioconda::pypgatk=0.0.10
  - conda-forge::coreutils=8.31
  - conda-forge::git-lfs=2.13.2
  - conda-forge::git=2.30.0
